export interface ThemeInfo {
  id: string
  name: string
  description: string
  previews: string[]
  repo?: string
  tags?: string[]
}

export const official: ThemeInfo[] = [
  {
    id: "default",
    name: "Default",
    description: "The minimalism default theme for Slidev",
    repo: "https://github.com/slidevjs/themes/tree/main/packages/theme-default",
    previews: [
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-default/01.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-default/02.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-default/06.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-default/08.png",
    ],
    tags: ["minimalism", "dark", "light"],
  },
  {
    id: "seriph",
    name: "Seriph",
    description: "A more formal looking theme using Serif fonts",
    repo: "https://github.com/slidevjs/themes/tree/main/packages/theme-seriph",
    previews: [
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-seriph/01.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-seriph/02.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-seriph/03.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-seriph/08.png",
    ],
    tags: ["minimalism", "dark", "light"],
  },
  {
    id: "apple-basic",
    name: "Apple Basic",
    description: "Inspired by the Basic Black/White theme from Apple Keynote",
    repo: "https://github.com/slidevjs/themes/tree/main/packages/theme-apple-basic",
    previews: [
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-apple-basic/01.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-apple-basic/02.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-apple-basic/03.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-apple-basic/09.png",
    ],
    tags: ["minimalism", "dark", "light"],
  },
  {
    id: "bricks",
    name: "Bricks",
    description: "Building bricks",
    repo: "https://github.com/slidevjs/themes/tree/main/packages/theme-bricks",
    previews: [
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-bricks/01.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-bricks/04.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-bricks/06.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-bricks/05.png",
    ],
    tags: ["light"],
  },
  {
    id: "shibainu",
    name: "Shibainu",
    description: "Meow!",
    repo: "https://github.com/slidevjs/themes/tree/main/packages/theme-shibainu",
    previews: [
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-shibainu/01.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-shibainu/03.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-shibainu/04.png",
      "https://cdn.jsdelivr.net/gh/slidevjs/themes@main/screenshots/theme-shibainu/09.png",
    ],
    tags: ["dark"],
  },
]

export const community: ThemeInfo[] = [
  {
    id: "academic",
    name: "Academic",
    description: "Academic presentations with Slidev made simple",
    repo: "https://github.com/alexanderdavide/slidev-theme-academic",
    previews: [
      "https://cdn.jsdelivr.net/gh/alexanderdavide/slidev-theme-academic@assets/example-export/01.png",
      "https://cdn.jsdelivr.net/gh/alexanderdavide/slidev-theme-academic@assets/example-export/02.png",
      "https://cdn.jsdelivr.net/gh/alexanderdavide/slidev-theme-academic@assets/example-export/08.png",
      "https://cdn.jsdelivr.net/gh/alexanderdavide/slidev-theme-academic@assets/example-export/04.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "cobalt",
    name: "Cobalt",
    description: "Deep cobalt blue color scheme with framed layouts",
    repo: "https://github.com/alecfe/slidev-theme-cobalt",
    previews: [],
    tags: ["dark"],
  },
  {
    id: "dracula",
    name: "Dracula",
    description: "One of the best dark themes meets Slidev",
    repo: "https://github.com/jd-solanki/slidev-theme-dracula",
    previews: [
      "https://cdn.jsdelivr.net/gh/jd-solanki/slidev-theme-dracula/screenshots/screenshot-1.png",
      "https://cdn.jsdelivr.net/gh/jd-solanki/slidev-theme-dracula/screenshots/screenshot-2.png",
      "https://cdn.jsdelivr.net/gh/jd-solanki/slidev-theme-dracula/screenshots/screenshot-3.png",
      "https://cdn.jsdelivr.net/gh/jd-solanki/slidev-theme-dracula/screenshots/screenshot-4.png",
      "https://cdn.jsdelivr.net/gh/jd-solanki/slidev-theme-dracula/screenshots/screenshot-5.png",
    ],
    tags: ["dark", "minimalism"],
  },
  {
    id: "eloc",
    name: "Eloc",
    description: "Focus on writing, present in a concise style",
    repo: "https://github.com/zthxxx/slides/tree/master/packages/slidev-theme-eloc",
    previews: [
      "https://cdn.jsdelivr.net/gh/zthxxx/slides@master/packages/slidev-theme-eloc/screenshot/01.png",
      "https://cdn.jsdelivr.net/gh/zthxxx/slides@master/packages/slidev-theme-eloc/screenshot/02.png",
      "https://cdn.jsdelivr.net/gh/zthxxx/slides@master/packages/slidev-theme-eloc/screenshot/03.png",
      "https://cdn.jsdelivr.net/gh/zthxxx/slides@master/packages/slidev-theme-eloc/screenshot/04.png",
      "https://cdn.jsdelivr.net/gh/zthxxx/slides@master/packages/slidev-theme-eloc/screenshot/05.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "field-manual",
    name: "Field Manual",
    description: "A 24-layout theme modeled on vintage military field manuals",
    repo: "https://github.com/pjdoland/slidev-theme-field-manual",
    previews: [
      "https://raw.githubusercontent.com/pjdoland/slidev-theme-field-manual/main/screenshots/1.jpg",
      "https://raw.githubusercontent.com/pjdoland/slidev-theme-field-manual/main/screenshots/2.jpg",
      "https://raw.githubusercontent.com/pjdoland/slidev-theme-field-manual/main/screenshots/3.jpg",
      "https://raw.githubusercontent.com/pjdoland/slidev-theme-field-manual/main/screenshots/4.jpg",
    ],
    tags: ["light", "dark", "vintage"],
  },
  {
    id: "frankfurt",
    name: "Frankfurt",
    description: "Inspired by the LaTeX Beamer theme Frankfurt",
    repo: "https://github.com/MuTsunTsai/slidev-theme-frankfurt",
    previews: [
      "https://cdn.jsdelivr.net/gh/MuTsunTsai/slidev-theme-frankfurt/screenshots/01.png",
      "https://cdn.jsdelivr.net/gh/MuTsunTsai/slidev-theme-frankfurt/screenshots/04.png",
      "https://cdn.jsdelivr.net/gh/MuTsunTsai/slidev-theme-frankfurt/screenshots/06.png",
      "https://cdn.jsdelivr.net/gh/MuTsunTsai/slidev-theme-frankfurt/screenshots/07.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "geist",
    name: "Vercel / Geist",
    description: "A theme based on Vercel's design system",
    repo: "https://github.com/nico-bachner/slidev-theme-geist",
    previews: [
      "https://cdn.jsdelivr.net/gh/nico-bachner/slidev-theme-geist@main/example-export/01.png",
      "https://cdn.jsdelivr.net/gh/nico-bachner/slidev-theme-geist@main/example-export/02.png",
      "https://cdn.jsdelivr.net/gh/nico-bachner/slidev-theme-geist@main/example-export/03.png",
      "https://cdn.jsdelivr.net/gh/nico-bachner/slidev-theme-geist@main/example-export/04.png",
      "https://cdn.jsdelivr.net/gh/nico-bachner/slidev-theme-geist@main/example-export/05.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "neocarbon",
    name: "Neocarbon",
    description: "Premium dark theme with cinematic animations and glass morphism",
    repo: "https://github.com/nicepkg/slidev-theme-neocarbon",
    previews: [],
    tags: ["dark"],
  },
  {
    id: "neversink",
    name: "Neversink",
    description: "Education and academia oriented theme with whimsical elements",
    repo: "https://github.com/gureckis/slidev-theme-neversink",
    previews: [
      "https://gureckis.github.io/slidev-theme-neversink/screenshots/2.png",
      "https://gureckis.github.io/slidev-theme-neversink/screenshots/6.png",
      "https://gureckis.github.io/slidev-theme-neversink/screenshots/8.png",
      "https://gureckis.github.io/slidev-theme-neversink/screenshots/15.png",
    ],
    tags: ["light", "academic"],
  },
  {
    id: "nord",
    name: "Nord",
    description: "Based on the Nord color palette",
    repo: "https://github.com/oller/slidev-theme-nord",
    previews: [
      "https://raw.githubusercontent.com/oller/slidev-theme-nord/HEAD/example-export/1.png",
      "https://raw.githubusercontent.com/oller/slidev-theme-nord/HEAD/example-export/2.png",
      "https://raw.githubusercontent.com/oller/slidev-theme-nord/HEAD/example-export/3.png",
      "https://raw.githubusercontent.com/oller/slidev-theme-nord/HEAD/example-export/4.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "penguin",
    name: "Penguin",
    description: "A Penguin theme for Slidev",
    repo: "https://github.com/alvarosabu/slidev-theme-penguin",
    previews: [
      "https://cdn.jsdelivr.net/gh/alvarosaburido/slidev-theme-penguin@master/screenshots/dark/01.png",
      "https://cdn.jsdelivr.net/gh/alvarosaburido/slidev-theme-penguin@master/screenshots/light/02.png",
      "https://cdn.jsdelivr.net/gh/alvarosaburido/slidev-theme-penguin@master/screenshots/light/06.png",
      "https://cdn.jsdelivr.net/gh/alvarosaburido/slidev-theme-penguin@master/screenshots/light/05.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "purplin",
    name: "Purplin",
    description: "Theme with bar bottom component, based on purple color",
    repo: "https://github.com/moudev/slidev-theme-purplin",
    previews: [
      "https://i.imgur.com/BX3TpEc.png",
      "https://i.imgur.com/mqqRi1F.png",
      "https://i.imgur.com/fwm2785.png",
      "https://i.imgur.com/m8eemKt.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "scholarly",
    name: "Scholarly",
    description: "LaTeX Beamer-style styling for scholarly presentations",
    repo: "https://github.com/jxpeng98/slidev-theme-scholarly",
    previews: [
      "https://raw.githubusercontent.com/jxpeng98/slidev-theme-scholarly/HEAD/images/themes/classic-blue/1.png",
      "https://raw.githubusercontent.com/jxpeng98/slidev-theme-scholarly/HEAD/images/themes/oxford/1.png",
      "https://raw.githubusercontent.com/jxpeng98/slidev-theme-scholarly/HEAD/images/themes/cambridge/1.png",
      "https://raw.githubusercontent.com/jxpeng98/slidev-theme-scholarly/HEAD/images/themes/princeton/1.png",
    ],
    tags: ["academic"],
  },
  {
    id: "swiss-ai-hub",
    name: "Swiss AI Hub",
    description: "Professional theme with Swiss AI-Hub branding and gradient backgrounds",
    repo: "https://github.com/bbvch-ai/slidev-theme-swiss-ai-hub",
    previews: [],
    tags: ["dark"],
  },
  {
    id: "the-unnamed",
    name: "The Unnamed",
    description: "A theme based on The unnamed VS Code theme",
    repo: "https://github.com/estruyf/slidev-theme-the-unnamed",
    previews: [
      "https://cdn.jsdelivr.net/gh/estruyf/slidev-theme-the-unnamed@main/assets/cover.png",
      "https://cdn.jsdelivr.net/gh/estruyf/slidev-theme-the-unnamed@main/assets/about-me.png",
      "https://cdn.jsdelivr.net/gh/estruyf/slidev-theme-the-unnamed@main/assets/default.png",
      "https://cdn.jsdelivr.net/gh/estruyf/slidev-theme-the-unnamed@main/assets/section.png",
    ],
    tags: ["dark"],
  },
  {
    id: "unicorn",
    name: "Unicorn",
    description: "Based on Dawntraoz website design",
    repo: "https://github.com/dawntraoz/slidev-theme-unicorn",
    previews: [
      "https://cdn.jsdelivr.net/gh/Dawntraoz/slidev-theme-unicorn@master/screenshots/dark-theme-intro.png",
      "https://cdn.jsdelivr.net/gh/Dawntraoz/slidev-theme-unicorn@master/screenshots/light-theme-cover.png",
      "https://cdn.jsdelivr.net/gh/Dawntraoz/slidev-theme-unicorn@master/screenshots/dark-theme-image-centered.png",
      "https://cdn.jsdelivr.net/gh/Dawntraoz/slidev-theme-unicorn@master/screenshots/dark-theme-center-without-header-footer.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "vibe",
    name: "Vibe",
    description: "Dark-mode theme with glassmorphism and neon accents",
    repo: "https://github.com/nicepkg/slidev-theme-vibe",
    previews: [],
    tags: ["dark"],
  },
  {
    id: "vuetiful",
    name: "Vuetiful",
    description: "A Vue-inspired theme for Slidev",
    repo: "https://github.com/LinusBorg/slidev-theme-vuetiful",
    previews: [
      "https://cdn.jsdelivr.net/gh/LinusBorg/slidev-theme-vuetiful@main/screenshots/cover-alt.png",
      "https://cdn.jsdelivr.net/gh/LinusBorg/slidev-theme-vuetiful@main/screenshots/section.png",
      "https://cdn.jsdelivr.net/gh/LinusBorg/slidev-theme-vuetiful@main/screenshots/big-points.png",
      "https://cdn.jsdelivr.net/gh/LinusBorg/slidev-theme-vuetiful@main/screenshots/quote.png",
    ],
    tags: ["dark", "light"],
  },
  {
    id: "zhozhoba",
    name: "Zhozhoba",
    description: "A zhozhoba theme for Slidev",
    repo: "https://github.com/thatoranzhevyy/slidev-theme-zhozhoba",
    previews: [
      "https://cdn.jsdelivr.net/gh/thatoranzhevyy/slidev-theme-zhozhoba@master/slides-export/01.png",
      "https://cdn.jsdelivr.net/gh/thatoranzhevyy/slidev-theme-zhozhoba@master/.github/dark.png",
      "https://cdn.jsdelivr.net/gh/thatoranzhevyy/slidev-theme-zhozhoba@master/slides-export/02.png",
      "https://cdn.jsdelivr.net/gh/thatoranzhevyy/slidev-theme-zhozhoba@master/slides-export/03.png",
    ],
    tags: ["dark", "light"],
  },
]
